# Generated by Django 5.2.4 on 2025-07-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('noticia_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=85)),
                ('subtitulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=50)),
                ('categorias', models.ManyToManyField(to='noticias.categoria')),
            ],
        ),
    ]
