# Generated by Django 5.2.4 on 2025-07-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='descripcion',
        ),
    ]
