# Generated by Django 5.2.4 on 2025-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_description_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
