# Generated by Django 5.2.4 on 2025-07-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
